# Generated by Django 4.2.5 on 2023-10-29 06:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="school",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("FIO", models.CharField(max_length=70, verbose_name="ФИО")),
                ("tel", models.IntegerField(verbose_name="Телефон")),
                ("email", models.EmailField(max_length=254, verbose_name="email")),
                ("INN", models.PositiveIntegerField(verbose_name="INN")),
                (
                    "name",
                    models.CharField(
                        max_length=50, verbose_name="Название организации"
                    ),
                ),
                (
                    "adress",
                    models.CharField(max_length=200, verbose_name="Адрес организации"),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Организация",
                "verbose_name_plural": "Организация",
            },
        ),
    ]
