# Generated by Django 4.2.5 on 2023-10-28 07:12

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Schools",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("FIO", models.CharField(max_length=70, verbose_name="ФИО")),
                ("tel", models.IntegerField(verbose_name="Телефон")),
                ("email", models.EmailField(max_length=254, verbose_name="email")),
                ("INN", models.PositiveIntegerField(verbose_name="Телефон")),
                (
                    "name",
                    models.CharField(
                        max_length=50, verbose_name="Название организации"
                    ),
                ),
                (
                    "adress",
                    models.CharField(max_length=200, verbose_name="Адрес организации"),
                ),
            ],
            options={
                "verbose_name": "Организация",
                "verbose_name_plural": "Организация",
            },
        ),
    ]
