# Generated by Django 4.2.5 on 2023-10-28 07:14

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("Site", "0001_initial"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Schools",
            new_name="school",
        ),
    ]
