# Generated by Django 4.2.6 on 2023-10-28 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Site', '0002_rename_schools_school'),
    ]

    operations = [
        migrations.AlterField(
            model_name='school',
            name='INN',
            field=models.PositiveIntegerField(verbose_name='INN'),
        ),
    ]
